name: Deployment

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment:
      name: render
      url: https://ntpu-id.onrender.com
  
