name: Wake Bot
on:
  schedule: 
    - cron: '*/20 0-14 * * 1-5'
    - cron: '*/20 1-9 * * 0,6'
  workflow_dispatch:
      
jobs:
  wake-up:
    runs-on: ubuntu-latest
    steps:
      - name: HTTP request
        run: curl https://ntpu-id.herokuapp.com/
