name: Wake Bot
on:
  schedule:
    - cron: "*/15 0-14 * * *"
  workflow_dispatch:
      
jobs:
  wake-up:
    runs-on: ubuntu-latest
    steps:
      - name: HTTP request
        run: curl https://ntpu-id.onrender.com/
